### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by ghost** [andr3w321/espn_scraper#3]
when running the example.py script using python 3.11 the following error occurs:

Traceback (most recent call last):
  File "C:\...\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)

I've researched the JSON error online and it appears that something is not being parsed correctly in JSON?

Any help is greatly appreciated. Thank you!

**Comment by ghost** [comment]
this was resolved by updating python
